### ISSUE TITLE
Implement the innopoints transferring

### ISSUE THREAD

**Issue by illright** [illright/innopoints-backend#121]
This should be an endpoint receiving an email and a password, computing the hash and validating it, and in case of a match with an account from the old DB, transferring the innopoints to the currently logged in user, as well as deleting that profile record from the old DB.

We can either extract the essential data (username, pwd_hash, balance) from the old DB and store it in the new one for ease of access (as well as the ability for people to reclaim the innopoints that were lost due to the new DB being somehow dropped), or connect to the old DB directly.

**Comment by aabounegm** [comment]
The old DB is just an SQLite file, so we can copy it over SSH and use it directly using the built-in sqlite3 module.
We can also export the important info as CSV, but it doesn't have the querying ability out of the box.
I suggest the first method

**Comment by illright** [comment]
Alright, so now the frontend expects the following:
`POST /api/v1/reclaim-innopoints`, with the body being a JSON object `{ email, password }`.
If the request was successful, the response should be the amount of reclaimed innopoints, without any objects wrapping it, just a number literal. If the username/password did not match, should return 403.
