### ISSUE TITLE
Include timezone in timestamp

### ISSUE THREAD

**Issue by aabounegm** [illright/innopoints-backend#13]
Timestamps currently default to GMT+0, and are saved without the timezone information. They should be modified to either store the timezone information (preferred), or to simply use the GMT+3 timezone of Innopolis.

**Comment by illright** [comment]
It's a matter of adding a meta parameter to all affected schemas:
```python
class Meta:
    datetimeformat = '%Y-%m-%dT%H:%M:%SZ'
```

The `Z` modifier at the end states that the time is in UTC.

**Comment by illright** [comment]
Affected schemas:
* `ActivitySchema`
* `ApplicationSchema`
* `ProductSchema`
* `ProjectSchema`
* `StockChangeSchema`

**Comment by aabounegm** [comment]
I think it is not only about the schemas, but the model itself as well, since the generated column type in PostgreSQL is "timestamp without timezone". The solution is probably in passing the `timezone=True` kwarg to the `db.Datetime` type in models column definitions.
