### ISSUE TITLE
Draft activities

### ISSUE THREAD

**Issue by illright** [illright/innopoints-backend#135]
## Issues

* maintaining an internal activity list is cumbersome and very bug-prone
* unfinished activities are not preserved (reloading a page when creating a template project causes the template to lose all its unsaved activities)

## Proposal

Add a `draft` property to the activity object. This property will control whether the activity is finished and visible to the applicants.

This will force us to allow more flexibility in the database by lifting some constraints and moving their enforcement to the application level.

A draft activity cannot be applied to and is not listed in the project page to non-moderators. A process of converting a draft activity into a non-draft activity is irreversible: once the activity is published, it cannot be brought back to the draft stage.

An non-draft activity must:

* have a non-empty name
* have a start date and an end date

A project may have draft activities at any stage, but only non-draft activities can be applied to.

## Changes

* **Remove the uniqueness constraint on the project name**
  We don't use it for addressing, and in this way we can create a draft project right away, without any input from the user
* **Allow the project name to be nullable**
* **Remove the uniqueness constraint on the activity name within the project**
  We don't use it for addressing, the distinction of internal activities is done with a separate property, and if the creator wishes to create two or more activities with the same name, they probably know what they're doing.
* **Add a `draft` property to the Activity model**
  Have it non-nullable and default to `True`.

**Comment by aabounegm** [comment]
> This will force us to allow more flexibility in the database by lifting some constraints and moving their enforcement to the application level.

Not necessarily. We can use conditional constraints. 
Same thing applies to the name. Either it (project/activity) is a draft and the name can be empty, or the name is unique. For that, I would prefer that the name is not nullable but defaults to empty string

**Comment by illright** [comment]
> We can use conditional constraints.

Those will have to cross tables, which is a pain, if at all possible

> For that, I would prefer that the name is not nullable but defaults to empty string

How is it better? To me, a `null` value conveys a meaning of "not specified" more clearly than an empty string

**Comment by aabounegm** [comment]
> Those will have to cross tables

Why so? I was referring to the existing constraints on individual tables. They can be just like they are right now, just with an extra condition that checks if `draft = True`. A SQL example can look like this:
```sql
CHECK
(
    draft = True
    OR name IS NOT NULL
)
```
I am not really sure how to do the same with `UNIQUE` constraint, but it can still be done using `COUNT`.

**Comment by illright** [comment]
Well, I honestly don't know if it's necessary. Check out the PR and let me know there
