### ISSUE TITLE
Fix file manager

### ISSUE THREAD

**Issue by aabounegm** [illright/innopoints-backend#21]
Change the file manager module to use local file system for storage instead of Amazon S3

**Comment by illright** [comment]
No, wait, Heroku must use S3 as its file system is ephemeral. Perhaps we should make this environment-dependent?

**Comment by aabounegm** [comment]
TODO:
- Get the S3 file manager back again
- Modularize the file manager to allow different implementations
- Use the correct file manager depending on the environment
