### ISSUE TITLE
Implement the notification system

### ISSUE THREAD

**Issue by illright** [illright/innopoints-backend#33]
For now, just the creation of notifications on certain events over the website and a set of endpoints to list, dismiss, etc.

To do:
**Notification types:**
- [x] purchase_status_changed
- [x] new_arrivals
- [x] application_status_changed
- [x] claim_innopoints
- [x] project_review_status_changed
- [x] added_as_moderator
- [x] all_feedback_in
- [x] out_of_stock
- [x] new_purchase
- [x] project_review_requested
- [x] service
- [x] manual_transaction

**Endpoints:**
- [x] list my notifications
- [ ] pagination on notification listing ^
- [x] mark a notification as read

**Comment by aabounegm** [comment]
To do:
- [ ] purchase_status_changed
- [ ] new_arrivals
- [ ] application_status_changed
- [ ] claim_innopoints
- [ ] project_review_status_changed
- [ ] added_as_moderator
- [ ] all_feedback_in
- [ ] out_of_stock
- [ ] new_purchase
- [ ] project_review_requested
- [ ] service
