### ISSUE TITLE
Create endpoints for manual adding of innopoints

### ISSUE THREAD

**Issue by aabounegm** [illright/innopoints-backend#34]
Admins have a page to manually add/subtract innopoints from a set of users. Implement the endpoint, with its parameters as follows:
```js
{
    "emails": ["student1@innopolis.university", "student2@innopolis.university"],
    "amount": 750,
    "message": "" //or null. This is used to send users a custom notification
}
```

**Comment by illright** [comment]
I was just doing this, and I had a different idea of an API:
`/profile/{email}/balance`
```js
{
  "change",
}
```

**Comment by illright** [comment]
I just think that bulk operations are not that frequent to break away from the `/profile/{email}` prefix. And the message passing is a different, separate mechanism, not to be mixed with this.

**Comment by aabounegm** [comment]
So you want to iterate over all emails in the frontend and send a `POST /profile/<email>/balance` request and a `POST /notifications` request to every single one?

**Comment by illright** [comment]
Precisely
