### ISSUE TITLE
Add missing views

### ISSUE THREAD

**Issue by aabounegm** [illright/innopoints-backend#35]
The endpoints that should be done and are not yet covered by any issue
- [ ] everything about viewing account (name, points, statistics, ...)
- [ ] edit account
- [ ] get a product (with all its varieties)
- [x] create project from template
- [ ] get a project (needs testing)
- [ ] filters and orderings for listing projects (ex: review_status=pending for admins)
- [ ] list my projects (meaning projects created by the current user in any stage, or non-draft ones the user moderates)

**Comment by illright** [comment]
Getting a product is pretty much not needed, since the list operation gives all the info it can.
Creating a project from a template is a front-end feature, the templates aren't actually stored in the DB.

**Comment by aabounegm** [comment]
But in listing we don't need all information. For example, we don't show description, sizes, purchase count, or any images but the first. Also, we want the users to be able to navigate to something like `/product/8` (especially to share this link with others or bookmark a specific product) without having to load all of the products

**Comment by illright** [comment]
Well...
The reason I thought we'd get away with no detail is because I didn't want to bother separating stuff like images. But okay, fine, let's do this.

**Comment by illright** [comment]
By the way, when would we want to request the projects that we created?

**Comment by aabounegm** [comment]
not sure. maybe part of the timeline? I can see it being used in the frontend in the future (part of profile or whatever), but not in the current version. it's not a priority

**Comment by illright** [comment]
I find this issue too broad, closing it in favor of #31, #47, #48, #49, #53.
