### ISSUE TITLE
Project moderators need to get innopoints

### ISSUE THREAD

**Issue by aabounegm** [illright/innopoints-backend#37]
Need to ask Andrey how exactly do project moderators get innopoints on their project. What factors determine the number of points awarded? Does he need to verify it (like an activity) or should all moderators get the points automatically after project finalization? Is it the same for the moderators as for the creator?

**Comment by illright** [comment]
As far as I remember from talking to him, it's also a matter of work hours at the regular 70 ipt/h rate. I've added a form for it in the markup [here](https://illright.github.io/innopoints-markup/view-project-finalizing.html), this could just be a field in the JSON for the times of project review.

**Comment by aabounegm** [comment]
And in implementation, do we create a special activity for it or give it some special handling?

**Comment by illright** [comment]
I say we give it special handling. Making it an activity would be too tedious. Perhaps an extra table and a few amendments to the API could work.

**Comment by aabounegm** [comment]
Perhaps make it part of the project_moderation table? and automatically add a transaction for it (if applicable) so we don't have to calculate innopoints of a person from 2 sources

**Comment by illright** [comment]
Well, I was thinking of a transaction too, but you're right about the fact that we can store it in the moderation table

**Comment by illright** [comment]
The most reasonable way to go is to introduce special internal activities. For that we need to:
- [x] Add a DB column for the `internal` flag
- [x] Handle creation of such activities on project creation
- [x] Disallow editing and deleting such activities
- [x] Disallow creating internal activities
- [x] Disallow applying to such activities
- [x] Disallow taking applications back
- [x] Create moderator applications on the transition from ongoing to finalizing 
- [x] Pass the ID of the application to the timeline entry to allow for giving feedback
