### ISSUE TITLE
Transform certain POST endpoints to PATCH

### ISSUE THREAD

**Issue by illright** [illright/innopoints-backend#40]
Sticking to the guideline [here](https://stackoverflow.com/a/31698882/5726823), it's best to review the existing endpoints to see if `PATCH` is a better candidate for a method.

**Comment by aabounegm** [comment]
Possible candidates:
- `/projects/{project_id}/publish`
- `/account/{email}/balance`, that one's tricky. while it technically creates a new transaction, the name suggests that it _edits_ the balance of the user.
- `/products/{product_id}/varieties/{variety_id}/purchase`. also not sure. it's name doesn't implying creating anything, but it's also not editing anything

**Comment by illright** [comment]
I'd say change the first two and keep the last one

**Comment by aabounegm** [comment]
I agree

**Comment by aabounegm** [comment]
Additionally, I think it will be better if the updated object is returned instead of NO_PAYLOAD

**Comment by illright** [comment]
Disagree here. I mean, _we've gone this far with returning the updated object on other modifications_, though I felt from the start that this was redundant. The reason why I wouldn't want it here is because the modification done by those methods is so small and defined that it just isn't worth the bandwith and memory spent on it

**Comment by aabounegm** [comment]
I know it is small, but it is still useful for the frontend to ensure that the change took place, and to just take the new object from the response and put it entirely in place of the old one.

**Comment by illright** [comment]
The frontend ensures that the change took place by observing the status code, which is 204, which is a success) as for the new object from the response, that's what I'm talking about. This kinda seems to me like frontend laziness, because I would update the object myself if I was to be writing the frontend. So I see no real use apart from letting the frontend slip one more time
