### ISSUE TITLE
Refactor the lifetime stages

### ISSUE THREAD

**Issue by illright** [illright/innopoints-backend#45]
Currently, the lifetime stage can be draft, ongoing or past, while the interface works with lifetime stages: draft, ongoing, finalizing, finished. The new lifetime stage can be obtained from the old lifetime stage and the review status, but this is tedious and unintuitive.

**Comment by aabounegm** [comment]
How about "under_review" instead of "finalizing"?

**Comment by illright** [comment]
It's not always under review when it's finalizing. Besides, I already got this naming deep into the markup, so just keep it)

**Comment by aabounegm** [comment]
Ah, so this task is about changing the enum values in the backend?

**Comment by illright** [comment]
Yesss
