### ISSUE TITLE
Implement changing the lifetime stage of projects

### ISSUE THREAD

**Issue by illright** [illright/innopoints-backend#52]
Related to #45

**Comment by aabounegm** [comment]
Do you mean `review_status` or `lifetime_stage`? If the former, doesn't issue #54 cover it?

**Comment by illright** [comment]
The lifetime stage. Buttons like finalize, accept during review and so on

**Comment by aabounegm** [comment]
Shouldn't this be done through `PATCH /project/{project_id}`, which is already there?

**Comment by illright** [comment]
Nah, that endpoint has a different purpose. Mixing it all together would be a disaster

**Comment by aabounegm** [comment]
Well, `PATCH /project/{project_id}` is about editing the attributes of the project. The lifetime stage is one such attribute.

**Comment by illright** [comment]
True, but this attribute is to be handled and validated very differently from the others. One must make sure that the transition from state to state is valid, that the conditions are met, and so on so forth, it is not just a matter of writing down the changes. In this sense `PATCH project` means edit project, and if we look at the frontend perspective, editing a project doesn't involve changing state. It is a different action, which is why it deserves a separate endpoint

**Comment by aabounegm** [comment]
in that case, you have to make sure that `PATCH /project` does not include any of those "special" attributes

**Comment by illright** [comment]
Precisely
https://github.com/illright/innopoints-backend/blob/master/innopoints/views/project.py#L204

**Comment by illright** [comment]
Then only one endpoint is left:
- [ ] Finalize the project
