### ISSUE TITLE
Gzip large response objects

### ISSUE THREAD

**Issue by aabounegm** [illright/innopoints-backend#59]
Use gzipping to compress responses
\* Note: make sure the frontend server also uses gzipping

**Comment by illright** [comment]
https://damyanon.net/post/flask-series-optimizations/
Seems awfully simple. The frontend does use gzipping, this is taken care of using the `compression` middleware:
```js
app()
  .use(
    ...
    compression({ threshold: 0 }),
    ...
  )
```

**Comment by aabounegm** [comment]
Do we even need Gzipping in the backend? JSON payloads are nothing compared to the HTML/CSS/JS served by the frontend

**Comment by illright** [comment]
Yeah, we don't
