### ISSUE TITLE
GET /products should specify MIME type

### ISSUE THREAD

**Issue by aabounegm** [illright/innopoints-backend#6]
To use the `json` property of the `request` object, the `Content-Type` header of the request has to be set to `application/json`, even when not passing json (when not needing "q" param).
The case when `request.json is None` should be properly handled. If JSON parsing is wanted regardless of headers, `request.get_json(force=True)` can be used instead (it can still return None when no JSON object is passed, though).
Also, it is best to keep "q" itself in the request params anyways instead of additional JSON.

**Comment by illright** [comment]
No longer relevant, the code has been rewritten.
