### ISSUE TITLE
Implement the email sending

### ISSUE THREAD

**Issue by illright** [illright/innopoints-backend#72]
Preferrably should be done in a separate thread to not slow down the server

**Comment by aabounegm** [comment]
@illright Is it really a priority? How about we put it in the backlog instead?

**Comment by illright** [comment]
@aabounegm Well, yeah, this is the main way of notification delivery

**Comment by illright** [comment]
Initially we could do it with SendGrid's API and then, with some negotiation with the IT dept., get the Outlook to work for us

**Comment by aabounegm** [comment]
Or we can use https://pythonhosted.org/Flask-Mail/ with any email (innopoints@gmail.com for example if 319 can't manage to get us a university one right away) until they give us one
